services:
    _defaults:
        autowire: true
        autoconfigure: true

    Neusta\Pimcore\PresentationBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']
