include:
    - project: NSD/p_pimcore/pimcore-ci-templates
      ref: 0.9.1
      file:
          - gitlab-ci/composer.yaml
          - gitlab-ci/cs-fixer.yaml
          - gitlab-ci/lint-twig.yaml
          - gitlab-ci/lint-yaml.yaml
          - gitlab-ci/phpunit.yaml

stages:
    - build
    - test
    - package

build:vendor:
    stage: build
    extends: .composer-install

test:security:
    stage: test
    extends: .composer-security
    needs:
        - build:vendor

test:code-style:
    stage: test
    extends: .php-cs-fixer
    needs:
        - build:vendor

test:lint-twig:
    stage: test
    extends: .lint-twig
    needs:
        - build:vendor

test:lint-yaml:
    stage: test
    extends: .lint-yaml
    needs:
        - build:vendor

test:phpunit:
    stage: test
    extends: .phpunit-with-coverage
    needs:
        - build:vendor

package:composer:
    stage: package
    extends: .composer-package-on-tag
    needs:
        - test:phpunit
